// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJOeX2Y7bDYbYpaidDdwswl-OdosvqHK8',
    appId: '1:118315960641:web:3900d06f2bf564f0aa79c0',
    messagingSenderId: '118315960641',
    projectId: 'evaluacion3-iot-flutter',
    authDomain: 'evaluacion3-iot-flutter.firebaseapp.com',
    databaseURL: 'https://evaluacion3-iot-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion3-iot-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThAhUDUwTLjdhbtpbaABX8KizpKodlJE',
    appId: '1:118315960641:android:d96c5579816f06a1aa79c0',
    messagingSenderId: '118315960641',
    projectId: 'evaluacion3-iot-flutter',
    databaseURL: 'https://evaluacion3-iot-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion3-iot-flutter.firebasestorage.app',
  );
}
